# Configuration for GitHub's automatic release notes
# See: https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes

changelog:
  exclude:
    labels:
      - ignore-for-release
      - dependencies
  categories:
    - title: 🚀 Features
      labels:
        - feature
        - enhancement
        - Semver-Minor
    - title: 🐛 Bug Fixes
      labels:
        - bug
        - bugfix
        - fix
    - title: ⚠️ Breaking Changes
      labels:
        - breaking-change
        - Semver-Major
    - title: 📚 Documentation
      labels:
        - documentation
        - docs
    - title: 🔧 Maintenance
      labels:
        - chore
        - refactor
        - test
    - title: 📦 Dependencies
      labels:
        - dependencies
    - title: 🌱 Other Changes
      labels:
        - "*" 