[toolchain]
# I really don't want to use nightly, but we have to, until:
# https://github.com/spiraldb/fastlanes/issues/45 is fixed.
channel = "nightly-2025-04-29"
components = ["rustfmt", "clippy", "rust-src", "miri"]
