name: "Rust Setup"
description: "Sets up Rust with sccache and caching"

runs:
  using: "composite"
  steps:
    - name: Configure runtime env
      shell: bash
      run: |
        echo "RUST_BACKTRACE=1" >> $GITHUB_ENV
        echo "CARGO_INCREMENTAL=0" >> $GITHUB_ENV
        echo "RUSTFLAGS=-C debuginfo=line-tables-only -C incremental=false" >> $GITHUB_ENV

    - name: Setup Rust toolchain
      shell: bash
      run: |
        echo "Installing nightly-2025-01-24"
        rustup toolchain install nightly-2025-01-24 --component rustfmt --component clippy --component rust-src --profile minimal --no-self-update
        rustup default nightly-2025-01-24
