name: Rust CI

on:
    push:
        branches:
            - main
            - dev
    pull_request:
        branches:
            - "*"

env:
    CARGO_TERM_COLOR: always
    RUST_BACKTRACE: 1
    RUSTFLAGS: "-C debuginfo=line-tables-only -C incremental=false"

jobs:
    check:
        name: Basic check
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: dtolnay/rust-toolchain@stable
              with:
                  components: clippy, rustfmt
            - uses: Swatinem/rust-cache@v2

            - name: Check formatting
              run: cargo fmt --all -- --check

            - name: Run clippy
              run: cargo clippy --all-targets --all-features -- -D warnings

    unit_test:
        name: Unit Test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: dtolnay/rust-toolchain@stable
            - uses: Swatinem/rust-cache@v2
            - name: Run tests
              run: cargo test --workspace
